# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Gamma density function
NULL

dgamma_rcpp <- function(x, mu, sigma) {
    .Call('_MasterThesis_dgamma_rcpp', PACKAGE = 'MasterThesis', x, mu, sigma)
}

dweibull_rcpp <- function(x, shape, scale) {
    .Call('_MasterThesis_dweibull_rcpp', PACKAGE = 'MasterThesis', x, shape, scale)
}

dlnorm_rcpp <- function(x, meanlog, sdlog) {
    .Call('_MasterThesis_dlnorm_rcpp', PACKAGE = 'MasterThesis', x, meanlog, sdlog)
}

dexp_rcpp <- function(x, rate, foo = 0) {
    .Call('_MasterThesis_dexp_rcpp', PACKAGE = 'MasterThesis', x, rate, foo)
}

dvm_rcpp <- function(x, mu, kappa) {
    .Call('_MasterThesis_dvm_rcpp', PACKAGE = 'MasterThesis', x, mu, kappa)
}

dwrpcauchy_rcpp <- function(x, mu, rho) {
    .Call('_MasterThesis_dwrpcauchy_rcpp', PACKAGE = 'MasterThesis', x, mu, rho)
}

mllk_cpp <- function() {
    .Call('_MasterThesis_mllk_cpp', PACKAGE = 'MasterThesis')
}

